openapi: 3.0.4
info:
  title: Swagger NodePop - OpenAPI 3.0
  description: |-
    This is a Wallapop Server version based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). 
servers:
  - url: http://localhost:3000/api-doc/

tags:
  - name: Login
    description: Login to show and edit products
  - name: Products
    description: Show, create and edit products

paths:
  /api/login:
    post:
      tags: 
        - Login
      description: Login with email and password
      operationId: login
      requestBody:
        description: Login
        content: 
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /api/products:
    get:
      tags: 
        - Products
      description: Show products belonging to the logged user
      operationId: showProducts
      Authorization: Bearer <token>
      security:
        -bearerAuth:  []
      responses: 
      '401':
        description: Access token is missing or invalid



components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: 1234
    Product:
      type: object
      properties:
        name:
          type: string
          example: Red Car
        price:
          type: number
          example: 25000
        image:
          type: image
        tags:
          type: Tags
    Tags:
      type: string []
  securitySchemes:
    bearerAuth: 
        type: http
        scheme: bearer
        bearerFormat: JWT
